[package]
name = "wasmcane"
version = "0.1.0"
authors = ["Sallar Kaboli <sallar.kaboli@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.11"
rcw = { path = "./rust-cardano/rcw/" }
